_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.8
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-x86_64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 512
compile:
    value: false
dataset:
    value: customer_sentiment
decay_lr:
    value: true
device:
    value: cpu
dropout:
    value: 0.1
dtype:
    value: float16
eval_interval:
    value: 100
eval_iters:
    value: 100
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 10
lr_decay_iters:
    value: 2000
max_iters:
    value: 2000
min_lr:
    value: 0.0001
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
out_dir:
    value: out-customer-sentiment
wandb_log:
    value: true
wandb_project:
    value: customer-sentiment
wandb_run_name:
    value: nanoGPT
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
