_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "6": 4.50.3
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 1
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 512
compile:
    value: false
dataset:
    value: gpt2_prepared
decay_lr:
    value: false
device:
    value: mps
dropout:
    value: 0
dtype:
    value: float16
eval_interval:
    value: 5
eval_iters:
    value: 40
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 32
init_from:
    value: gpt2
learning_rate:
    value: 3e-05
log_interval:
    value: 1
lr_decay_iters:
    value: 600000
max_iters:
    value: 20
min_lr:
    value: 6e-05
n_embd:
    value: 768
n_head:
    value: 12
n_layer:
    value: 12
out_dir:
    value: out-customer-gpt2
wandb_log:
    value: true
wandb_project:
    value: customer-sentiment
wandb_run_name:
    value: gpt2-ft-1743753659.425048
warmup_iters:
    value: 2000
weight_decay:
    value: 0.1
